import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Koryo Festival",
  description: "Generated by Koryo Fes Executive Committee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
